// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeightTracker.Api.Migrations;

namespace WeightTracker.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191119235937_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeightTracker.Api.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Standard"
                        });
                });

            modelBuilder.Entity("WeightTracker.Api.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kilograms",
                            ShortName = "kg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pounds",
                            ShortName = "lbs"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Stone",
                            ShortName = "st"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Stone & Pounds",
                            ShortName = "st lbs"
                        });
                });

            modelBuilder.Entity("WeightTracker.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UnitId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "harmeshuppal@gmail.com",
                            FirstName = "Mesh",
                            LastName = "Uppal",
                            Password = "ACOG+F5CQHf58fHvRpkgMdky7Fz1ZhIe/wPKXPbSO4chsdbKZ924fseQpUm3RtrQLw==",
                            RoleId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "test@gmail.com",
                            FirstName = "Test",
                            LastName = "Man",
                            Password = "ADZ13lG0RywDCqHtM3n6mtzigFJBND2QFE0frSsqa6gchP/ECB7FuUq9hhAvMYLZQg==",
                            RoleId = 2,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "test2@gmail.com",
                            FirstName = "Tester",
                            LastName = "Two",
                            Password = "AIsrTVzGzE+UoMu6jgn5fJdIJYj1TqIxMBW9pZOijvS0RajQmFY9bo6rpOJjq94YhA==",
                            RoleId = 2,
                            UnitId = 2
                        });
                });

            modelBuilder.Entity("WeightTracker.Api.Entities.WeighIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeighIns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2019, 9, 7, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            Value = "144"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2019, 9, 14, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            Value = "144"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2019, 9, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3,
                            Value = "160"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2019, 9, 21, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            Value = "143"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2019, 9, 23, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3,
                            Value = "159"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2019, 9, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            Value = "141.4"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2019, 10, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            Value = "141"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2019, 10, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            Value = "140"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2019, 10, 19, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            Value = "139.4"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2019, 10, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            Value = "138.2"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2019, 10, 30, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3,
                            Value = "158.5"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2019, 11, 2, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            Value = "138.4"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2019, 11, 9, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            Value = "137.6"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2019, 11, 16, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            Value = "136.4"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2019, 11, 19, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            Value = "136"
                        });
                });

            modelBuilder.Entity("WeightTracker.Api.Entities.User", b =>
                {
                    b.HasOne("WeightTracker.Api.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("WeightTracker.Api.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("WeightTracker.Api.Entities.WeighIn", b =>
                {
                    b.HasOne("WeightTracker.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
