// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeightTracker.Api.Migrations;

namespace WeightTracker.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191119212251_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeightTracker.Api.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Standard"
                        });
                });

            modelBuilder.Entity("WeightTracker.Api.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kilograms",
                            ShortName = "kg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pounds",
                            ShortName = "lbs"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Stone",
                            ShortName = "st"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Stone & Pounds",
                            ShortName = "st lbs"
                        });
                });

            modelBuilder.Entity("WeightTracker.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UnitId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "harmeshuppal@gmail.com",
                            FirstName = "Mesh",
                            LastName = "Uppal",
                            Password = "AA0Oot0r2AKu7+LUCYCgkxvmMp0V50DqlCfXZdzBoTobADPqXWeMdofIW8JV7716uQ==",
                            RoleId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "test@gmail.com",
                            FirstName = "Test",
                            LastName = "Man",
                            Password = "AGYn7eUm1TwWT4KOGoxLiimmmrKk/2KzXdydZsKTdoSSLT3LCi6ec5El+N0jWPOLTw==",
                            RoleId = 2,
                            UnitId = 1
                        });
                });

            modelBuilder.Entity("WeightTracker.Api.Entities.WeighIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeighIns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2019, 11, 19, 21, 22, 50, 166, DateTimeKind.Local).AddTicks(6161),
                            UserId = 2,
                            Value = "150"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2019, 11, 19, 21, 22, 50, 177, DateTimeKind.Local).AddTicks(2330),
                            UserId = 2,
                            Value = "160"
                        });
                });

            modelBuilder.Entity("WeightTracker.Api.Entities.User", b =>
                {
                    b.HasOne("WeightTracker.Api.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("WeightTracker.Api.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("WeightTracker.Api.Entities.WeighIn", b =>
                {
                    b.HasOne("WeightTracker.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
